basePath: /api/
host: localhost:8080
info:
  contact: {}
  description: This is small pet project for learning.
  title: People-food service
  version: "1.0"
paths: {}
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
