version: '3.9'

services:
  app:
    build: ./
    command: /bin/app
    container_name: pf-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_PASSWORD=postgres



  db:
    restart: always
    image: postgres:latest
    container_name: app-psql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - .:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/data
