

###
GET http://localhost:8080//api/person
Content-Type: application/json

{
  "name": "Игорь",
  "family_name": "Адамов"
}

###

GET http://localhost:8080//api/person
Content-Type: application/json

{

}

###
GET http://localhost:8080//api/person


###Get all func
GET http://localhost:8080//api/people


###Create with right body
POST http://localhost:8080//api/person
Content-Type: application/json

{
  "name": "Диман",
  "family_name": "Лыско",
  "food": [
    {
      "uuid": "d41b9758-f344-447f-b512-cc35b89c23e9",
      "name": "Пицца",
      "price": 7.85
    },
    {
      "uuid": "41b72d27-c250-4a3a-8c0b-8a7de570a564",
      "name": "Бурито",
      "price": 9.55
    },
    {
      "uuid": "63aa08fd-15b1-4cb6-af21-e1e40cbadc6c",
      "name": "Шавуха",
      "price": 15.22
    }]
}
###Delete with right body
DELETE http://localhost:8080//api/person
Content-Type: application/json

{
  "uuid": "040286e1-1b01-4dcf-b685-865673eaddeb",
  "name": "Диман",
  "family_name": "Рекрент"

}