

### Successful test: check response status is 200 and content-type is JSON
GET http://localhost:8080//api/person
Content-Type: application/json

{
  "name": "Игорь",
  "family_name": "Адамов"
}
> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Response content-type is json", function() {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });
%}

###Successful test: check response status is 400
GET http://localhost:8080//api/person
Content-Type: application/json

{

}
> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 400, "Response status is not 400");
    });

%}
###Successful test: check response status is 400
GET http://localhost:8080//api/person

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 400, "Response status is not 400");
    });
%}

### Successful test: check response status is 200 and content-type is JSON
GET http://localhost:8080//api/people

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Response content-type is json", function() {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });
%}

###Create with right body
POST http://localhost:8080//api/person
Content-Type: application/json

{
  "name": "Дима",
  "family_name": "Л",
  "food": [
    {
      "uuid": "d41b9758-f344-447f-b512-cc35b89c23e9",
      "name": "Пицца",
      "price": 7.85
    },
    {
      "uuid": "41b72d27-c250-4a3a-8c0b-8a7de570a564",
      "name": "Бурито",
      "price": 9.55
    },
    {
      "uuid": "63aa08fd-15b1-4cb6-af21-e1e40cbadc6c",
      "name": "Шавуха",
      "price": 15.22
    }]
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}
###Delete with right body
DELETE http://localhost:8080//api/person
Content-Type: application/json

{
  "uuid": "921e0731-26ac-468a-b92e-42d824d4607e",
  "name": "Диман",
  "family_name": "Рекрент"

}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
###
PATCH http://localhost:8080//api/person
Content-Type: application/json

{
  "uuid": "208a00f3-76a0-4290-8437-201a96639181",
  "name": "Диман",
  "family_name": "Лысый"
}

###
GET http://localhost:8080//api/food
Content-Type: application/json

{
"name": "",
"price": 0
}
> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Response content-type is json", function() {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });
%}